cursor #1e1b13
cursor_text_color #4b4739

foreground            #1e1b13
background            #fff9ee
selection_foreground  #ffffff
selection_background  #d2c6a1
url_color             #6e5d0e

color0   #16130b
color1   #790b00
color2   #0c5f00
color3   #998000
color4   #736009
color5   #c2b98c
color6   #6e5d0e
color7   #232321
color8   #6c6b67
color9   #c14530
color10  #178c05
color11  #a58b00
color12  #846d0e
color13  #c2b98c
color14  #8f8350
color15  #bfbeb8
