cursor #1b1c1c
cursor_text_color #464747

foreground            #1b1c1c
background            #faf9f9
selection_foreground  #ffffff
selection_background  #bfc8cb
url_color             #526166

color0   #121314
color1   #793048
color2   #215f28
color3   #999126
color4   #55656b
color5   #a9b1b4
color6   #526166
color7   #222323
color8   #696b6c
color9   #a55770
color10  #3f8c47
color11  #a59e31
color12  #5f727a
color13  #a9b1b4
color14  #778184
color15  #bbbebf
