include dank-tabs.conf
include catppuccin-frappe.conf
window_padding_width 5
hide_window_decorations yes
background_opacity 0.95
font_family JetBrains Maple Mono
font_size 11.0
symbol_map U+3000-U+303F,U+3400-U+4DBF,U+4E00-U+9FFF,U+F900-U+FAFF,U+FF00-U+FFEF Maple Mono NF CN
remember_window_size no
confirm_os_window_close 0
shell zsh
cursor_trail 1 
cursor_shape block
shell_integration no-cursor

