-- ========== which-key.nvim - 快捷键提示 ==========
-- 按下 Leader 键后显示可用的快捷键

return {
  "folke/which-key.nvim",
  lazy = false,
  priority = 1000,
  dependencies = {
    "echasnovski/mini.icons",
    "nvim-tree/nvim-web-devicons",
  },
  init = function()
    vim.o.timeout = true
    vim.o.timeoutlen = 1000 -- 1s，适配慢速按键习惯
  end,
  config = function()
    local wk = require("which-key")

    wk.setup({
      delay = 0, -- 按下 Leader 后立即显示 which-key
      triggers = {
        { "<auto>", mode = "nxso" },
        { "<leader>", mode = { "n", "v" } },
      },
      plugins = {
        marks = true,
        registers = true,
        spelling = {
          enabled = false,
        },
      },
      win = {
        border = "rounded",
      },
    })

    -- 新版 spec：使用 desc/group 字段
    wk.add({
      -- ========== g 前缀：跳转/LSP ==========
      { "g", group = "跳转/LSP" },
      -- LSP 相关
      { "gd", desc = "跳转到定义" },
      { "gh", desc = "悬浮文档" },
      { "gr", group = "LSP 重构" },
      { "grr", desc = "查找引用" },
      { "gra", desc = "代码操作", mode = { "n", "v" } },
      { "grn", desc = "重命名符号" },
      { "gri", desc = "查找实现" },
      -- Vim 内置 g 跳转
      { "gg", desc = "跳到文件开头" },
      { "gf", desc = "打开光标下文件" },
      { "gv", desc = "重选上次选区" },
      { "gi", desc = "跳到上次插入位置并插入" },
      { "g;", desc = "上一个修改位置" },
      { "g,", desc = "下一个修改位置" },
      { "gx", desc = "用系统程序打开" },
      { "go", desc = "跳到第 N 字节" },
      -- 搜索/匹配
      { "gn", desc = "选中下一个搜索匹配" },
      { "gN", desc = "选中上一个搜索匹配" },
      { "g*", desc = "模糊搜索光标词（向后）" },
      { "g#", desc = "模糊搜索光标词（向前）" },
      { "g%", desc = "反向匹配括号" },
      -- 移动
      { "ge", desc = "上一个单词尾" },
      { "gE", desc = "上一个字串尾" },
      { "gj", desc = "向下移动（屏幕行）" },
      { "gk", desc = "向上移动（屏幕行）" },
      { "g0", desc = "屏幕行首" },
      { "g$", desc = "屏幕行尾" },
      { "g^", desc = "屏幕行首（非空白）" },
      { "gm", desc = "屏幕行中间" },
      { "gM", desc = "文本行中间" },
      -- 大小写/格式化（操作符）
      { "gu", desc = "转小写", mode = { "n", "v" } },
      { "gU", desc = "转大写", mode = { "n", "v" } },
      { "g~", desc = "切换大小写", mode = { "n", "v" } },
      { "gw", desc = "格式化（保持光标）", mode = { "n", "v" } },
      { "gq", desc = "格式化文本", mode = { "n", "v" } },
      -- Tab 页
      { "gt", desc = "下一个标签页" },
      { "gT", desc = "上一个标签页" },
      -- 编辑
      { "gJ", desc = "合并行（不加空格）" },
      { "gp", desc = "粘贴并移动光标到末尾" },
      { "gP", desc = "向前粘贴并移动光标" },
      -- 信息
      { "ga", desc = "显示字符编码" },
      { "g8", desc = "显示 UTF-8 编码" },
      { "g<C-g>", desc = "显示光标位置信息" },
      -- 其他
      { "gI", desc = "在行首插入（第 1 列）" },

      -- ========== z 前缀：折叠/视图 ==========
      { "z", group = "折叠/视图" },
      -- 折叠操作
      { "za", desc = "切换当前折叠" },
      { "zA", desc = "递归切换折叠" },
      { "zK", desc = "预览折叠内容" },
      { "zc", desc = "关闭当前折叠" },
      { "zC", desc = "递归关闭折叠" },
      { "zo", desc = "打开当前折叠" },
      { "zO", desc = "递归打开折叠" },
      { "zM", desc = "关闭所有折叠" },
      { "zR", desc = "打开所有折叠" },
      { "zm", desc = "增加折叠层级" },
      { "zr", desc = "减少折叠层级" },
      { "zj", desc = "跳到下一个折叠" },
      { "zk", desc = "跳到上一个折叠" },
      { "zf", desc = "创建折叠", mode = { "n", "v" } },
      { "zd", desc = "删除当前折叠" },
      { "zD", desc = "递归删除折叠" },
      { "zE", desc = "清除所有折叠" },
      { "zi", desc = "切换折叠开关" },
      { "zn", desc = "禁用折叠" },
      { "zN", desc = "启用折叠" },
      { "zx", desc = "刷新折叠" },
      { "zX", desc = "重新应用折叠级别" },
      -- 视图/滚动
      { "zz", desc = "当前行居中" },
      { "zt", desc = "当前行置顶" },
      { "zb", desc = "当前行置底" },
      { "z.", desc = "居中并移到行首" },
      { "z<CR>", desc = "置顶并移到行首" },
      { "z-", desc = "置底并移到行首" },
      { "zl", desc = "向右滚动" },
      { "zh", desc = "向左滚动" },
      { "zL", desc = "向右滚动半屏" },
      { "zH", desc = "向左滚动半屏" },
      { "ze", desc = "向右滚到行尾" },
      { "zs", desc = "向左滚到行首" },
      -- 拼写
      { "zg", desc = "标记为正确拼写" },
      { "zw", desc = "标记为错误拼写" },
      { "z=", desc = "拼写建议" },

      -- ========== [ 前缀：向前导航 ==========
      { "[", group = "向前跳转" },
      -- 诊断/插件
      { "[d", desc = "上一个诊断" },
      { "[h", desc = "上一个 Git 改动" },
      { "[f", desc = "上一个函数" },
      { "[c", desc = "上一个类" },
      -- Vim 内置
      { "[(", desc = "上一个未匹配 (" },
      { "[{", desc = "上一个未匹配 {" },
      { "[[", desc = "上一个段首" },
      { "[]", desc = "上一个段尾" },
      { "[m", desc = "上一个方法开头" },
      { "[M", desc = "上一个方法结尾" },
      { "[s", desc = "上一个拼写错误" },
      { "[z", desc = "当前折叠开头" },
      { "[#", desc = "上一个未匹配 #if/#else" },
      { "[*", desc = "上一个注释开头" },
      { "[/", desc = "上一个注释开头" },
      -- Neovim 0.11 内置 unimpaired
      { "[a", desc = "上一个参数文件" },
      { "[A", desc = "第一个参数文件" },
      { "[b", desc = "上一个缓冲区" },
      { "[B", desc = "第一个缓冲区" },
      { "[l", desc = "上一个位置列表项" },
      { "[L", desc = "第一个位置列表项" },
      { "[q", desc = "上一个快速修复项" },
      { "[Q", desc = "第一个快速修复项" },
      { "[t", desc = "上一个标签" },
      { "[T", desc = "第一个标签" },
      { "[<C-L>", desc = "上一个位置列表文件" },
      { "[<C-Q>", desc = "上一个快速修复文件" },
      { "[<C-T>", desc = "上一个预览标签" },
      { "[<Space>", desc = "在上方添加空行" },
      { "[<", desc = "上一个 HTML 标签" },
      { "[%", desc = "上一个未匹配分组" },

      -- ========== ] 前缀：向后导航 ==========
      { "]", group = "向后跳转" },
      -- 诊断/插件
      { "]d", desc = "下一个诊断" },
      { "]h", desc = "下一个 Git 改动" },
      { "]f", desc = "下一个函数" },
      { "]c", desc = "下一个类" },
      -- Vim 内置
      { "])", desc = "下一个未匹配 )" },
      { "]}", desc = "下一个未匹配 }" },
      { "]]", desc = "下一个段首" },
      { "][", desc = "下一个段尾" },
      { "]m", desc = "下一个方法开头" },
      { "]M", desc = "下一个方法结尾" },
      { "]s", desc = "下一个拼写错误" },
      { "]z", desc = "当前折叠结尾" },
      { "]#", desc = "下一个未匹配 #endif" },
      { "]*", desc = "下一个注释结尾" },
      { "]/", desc = "下一个注释结尾" },
      -- Neovim 0.11 内置 unimpaired
      { "]a", desc = "下一个参数文件" },
      { "]A", desc = "最后一个参数文件" },
      { "]b", desc = "下一个缓冲区" },
      { "]B", desc = "最后一个缓冲区" },
      { "]l", desc = "下一个位置列表项" },
      { "]L", desc = "最后一个位置列表项" },
      { "]q", desc = "下一个快速修复项" },
      { "]Q", desc = "最后一个快速修复项" },
      { "]t", desc = "下一个标签" },
      { "]T", desc = "最后一个标签" },
      { "]<C-L>", desc = "下一个位置列表文件" },
      { "]<C-Q>", desc = "下一个快速修复文件" },
      { "]<C-T>", desc = "下一个预览标签" },
      { "]<Space>", desc = "在下方添加空行" },
      { "]>", desc = "下一个 HTML 标签" },
      { "]%", desc = "下一个未匹配分组" },

      -- ========== <leader> 基础操作 ==========
      { "<leader>w", desc = "保存文件" },
      { "<leader>q", desc = "退出" },
      { "<leader>j", desc = "合并行" },
      { "<leader>?", desc = "快捷键帮助" },
      { "<leader>+", desc = "增大窗口" },
      { "<leader>-", desc = "减小窗口" },
      { "<leader>=", desc = "均分窗口" },
      { "<leader>e", desc = "文件树" },
      { "<leader>m", desc = "Mason 包管理" },
      { "<leader>o", desc = "符号大纲" },
      { "<leader>y", desc = "剪切板历史" },
      -- <leader> 分组
      { "<leader>a", group = "AI/Claude" },
      { "<leader>b", group = "缓冲区" },
      { "<leader>c", group = "代码/CMake" },
      { "<leader>d", group = "调试/诊断" },
      { "<leader>f", group = "查找" },
      { "<leader>g", group = "Git" },
      { "<leader>h", group = "Git 变更块" },
      { "<leader>l", group = "标签/Grapple" },
      { "<leader>n", group = "笔记（Obsidian）" },
      { "<leader>P", group = "会话" },
      { "<leader>p", group = "Python/项目" },
      { "<leader>r", group = "渲染" },
      { "<leader>s", desc = "搜索替换（字面量）" },
      { "<leader>S", desc = "搜索替换（正则）" },
      { "<leader>t", group = "开关/终端" },
      { "<leader>u", group = "UI/通知" },
      { "<leader>tc", desc = "Copilot 开关" },
      { "<leader>tu", desc = "撤销历史树" },
      { "<leader>tf", desc = "浮动终端" },
      { "<leader>tv", desc = "垂直终端" },
      { "<leader>tg", desc = "Lazygit（已移至 <leader>gg）", hidden = true },
      { "<leader>aa", desc = "接受 Claude Diff" },
      { "<leader>ab", desc = "加入当前 Buffer" },
      { "<leader>ac", desc = "打开/关闭 Claude Code" },
      { "<leader>aC", desc = "继续 Claude 会话" },
      { "<leader>ad", desc = "拒绝 Claude Diff" },
      { "<leader>af", desc = "聚焦 Claude Code" },
      { "<leader>am", desc = "选择 Claude 模型" },
      { "<leader>ar", desc = "恢复 Claude 会话" },
      { "<leader>as", desc = "发送选区给 Claude", mode = "v" },
      { "<leader>pa", desc = "运行全部测试" },
      { "<leader>pc", desc = "运行提交前检查" },
      { "<leader>pC", desc = "运行 pre-commit 全量检查" },
      { "<leader>pd", desc = "调试当前测试" },
      { "<leader>pf", desc = "Ruff 格式检查" },
      { "<leader>pl", desc = "重跑上次测试" },
      { "<leader>pm", desc = "运行 mypy" },
      { "<leader>po", desc = "项目任务面板" },
      { "<leader>pO", desc = "测试输出面板" },
      { "<leader>pr", desc = "Ruff 检查" },
      { "<leader>pR", desc = "Ruff 自动修复" },
      { "<leader>ps", desc = "测试结构面板" },
      { "<leader>pt", desc = "运行当前 Python 测试" },
      { "<leader>pT", desc = "运行当前文件测试" },
      { "<leader>pv", desc = "选择 Python 虚拟环境" },
      { "<leader>M", group = "多光标" },
      { "<leader>x", group = "诊断列表" },
      -- Grapple 文件标签（数字键跳转）
      { "<leader>ll", desc = "标记文件（Grapple）" },
      { "<leader>lt", desc = "标签管理（Grapple）" },
      { "<leader>1", desc = "Grapple 标签 1" },
      { "<leader>2", desc = "Grapple 标签 2" },
      { "<leader>3", desc = "Grapple 标签 3" },
      { "<leader>4", desc = "Grapple 标签 4" },
      { "<leader>5", desc = "Grapple 标签 5" },
      { "<leader>6", desc = "Grapple 标签 6" },
      { "<leader>7", desc = "Grapple 标签 7" },
      { "<leader>8", desc = "Grapple 标签 8" },
      { "<leader>9", desc = "Grapple 标签 9" },
    })
  end,
}
